### ISSUE TITLE
A very fast frequency change will cause a restart

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#519] opened 2024-04-01 10:18 UTC
If I control the TEF6686 via WiFi and change the tuned frequency very quickly, the receiver restarts.  Tested so far with Stationlist-M.  Can someone verify in XDR-GTK?  v2.00.10

**Comment by PE5PVB** [comment] 2024-04-01 21:14
I'll look into this, is this only on AM or also on FM?

**Comment by Mike86-CZE** [comment] 2024-04-02 14:00
both.  FM and AM.

**Comment by andimik** [comment] 2024-04-02 18:25
I cannot reproduce it with xdr-gtk's spectrum when I scroll from one end to the other within less than one second.

[VID_20240402_202321.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/1128fc78-89e6-45f6-a9c1-295764d6c1db)

**Comment by Mike86-CZE** [comment] 2024-04-02 18:29
Try switching to AUTO or MEM and repeat.

**Comment by Mike86-CZE** [comment] 2024-04-02 18:31
According to the battery voltage indicator, wifi is not active, but it is connected via USB.  Try over WiFi.

**Comment by andimik** [comment] 2024-04-03 05:34
I have tested xdr-gtk with AUTO and MEM but had no problems with very fast frequency changes.

**Comment by PE5PVB** [comment] 2024-04-03 12:49
Found a memoryleak which could cause this. Try recompile the current branch and let me know.

**Comment by andimik** [comment] 2024-04-03 18:01
Even without the recent memory leak fix I could not reproduce it with Stationlist-M and WiFi.

Tested MEM and AUTO scrolling very very fast from left to the right FM band edge.

**Comment by Mike86-CZE** [comment] 2024-04-03 18:24
It took me quite a bit of work to trigger the error today.  Yesterday it happened much more often.  I have no idea why.

https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/d751570b-0411-4230-a269-ae1a975008d9

**Comment by andimik** [comment] 2024-04-03 18:43
According to the video please improve the WiFi signal. I fear this is causing the issue.

**Comment by Mike86-CZE** [comment] 2024-04-03 18:48
Yes, I'm pretty sure it affects the quality of the wifi connection.  I have now placed the TEF further away from the router (same location as yesterday) and managed to trigger the error three times in a short while.  However, earlier versions of fw did not have this problem.

**Comment by Mike86-CZE** [comment] 2024-04-03 19:19
> According to the video please improve the WiFi signal. I fear this is causing the issue.

We seem to have the same TEF model from the same manufacturer.  Did you modify the wifi antenna somehow for better range?  My TEF has very poor wifi range, only a few meters and preferably with line of sight.

**Comment by PE5PVB** [comment] 2024-04-03 20:25
Can you monitor the data on the USB port with a terminal program like Putty? It should show you a message at those reboots.

**Comment by andimik** [comment] 2024-04-03 21:32
A better Wi-Fi is not necessary. I am placing the mobile next to the the TEF.

**Comment by PE5PVB** [comment] 2024-04-03 21:34
Very curious about the serial output when the reboot happens....

**Comment by Mike86-CZE** [comment] 2024-04-06 07:32
I have found that if the screen saver is activated (display is off) then reboots do not occur.  Once I activate the screen again, it's easy to trigger the error/restart.

**Comment by PE5PVB** [comment] 2024-04-14 19:16
Please check again with v2.00.13b

**Comment by Mike86-CZE** [comment] 2024-04-15 15:28
So far I have not been able to trigger a reboot.  The bug really seems to be gone.  Good work.

**Comment by PE5PVB** [comment] 2024-04-29 10:09
OK. Let's close this one for now.

**Closed as completed by PE5PVB** 2024-04-29 10:09 UTC
