### ISSUE TITLE
AF-B mode is not displayed

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#395] opened 2023-11-08 05:26 UTC
In the latest update, the AF-B mode is no longer displayed.  Also, there are no S and R marks in the AF frequency list

**Comment by PE5PVB** [comment] 2023-11-08 13:50
I can't reproduce it. Are you sure the radiostation uses AF Method B? Did you wait long enough, it can take some time to detect AF-B.

**Comment by Yurij20** [comment] 2023-11-08 18:20
In the release for example from 10/25/2023 on 104.2 and 90.3, for example, AF-B is immediately displayed, in the latter the AF-B method is not visible at all.

**Comment by PE5PVB** [comment] 2023-11-08 19:54
In that version was a bug which false identified some channels as AF-B. I think the service you are checking doesn't have AF-B.

**Comment by Yurij20** [comment] 2023-11-08 20:25
Now we tested it with friends at one of the radio stations, specifying the af-b method, and on the latest firmware it doesn’t show up at all, alas. Below is the photo
![J-LqOmM25pE](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/fe41eacf-ae1d-489e-adde-03cd017958ed)
![6vkXbuycMAM](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/909bcb30-3ace-48b8-b5f2-2a3353bf41d9)
![NOG7ABVuZWo](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/0e3704a4-bcab-448a-9338-92108a72ab75)

**Comment by PE5PVB** [comment] 2023-11-08 20:26
Can you check with RDS Spy?

**Comment by Yurij20** [comment] 2023-11-08 20:35
![sZAwR5CsAVk](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/c0895b4a-8f81-4482-a243-609d6b181ce7)

**Comment by PE5PVB** [comment] 2023-11-08 21:06
It seems that this transmitter is using the AF-B the wrong way. To work correctly it should also send the same RDS data on the three other frequencies, and you should have more than 1 AF-B list. To prevent a wrong AF-B detection I added a check that at least one AF-B list for the current frequency is detected and one for another frequency is detected.

If I drop this, it can end up detecting false AF-B on some stations. Only alternative is to count the AF's which are the same after each listing, but that is a lot of work and can give faulty information on weak signals.

**Comment by Yurij20** [comment] 2023-11-08 21:30
Here is the situation with three af-b lists.  still doesn't display
![PAVGJrkYOhM](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/9cffaadd-998d-4d25-aca1-02f825fa942c)
![sfQGSekggDI](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/0b8a8e67-9010-4ba4-a167-9730af3e0a7c)
![VhpXVo7AsqU](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/d960e9bc-1b2e-4e7e-8d7d-327023de02f4)

**Comment by PE5PVB** [comment] 2023-11-08 21:31
Can you get me a MPX recording?

**Comment by Yurij20** [comment] 2023-11-08 21:36
ok) I’ll do it when I’m in another apartment, there’s an opportunity to record it.

**Comment by Yurij20** [comment] 2023-11-09 06:58
By the way, I have an MPX recording of one of our radio stations using the AF-B method.  This method also stopped being displayed on this station, although it was displayed perfectly in earlier builds.  I sent it to you earlier on another issue.  Check it out, if it doesn’t work then I’ll write another one later)

https://disk.yandex.ru/d/iMA0cRtA9pLCpA

**Comment by PE5PVB** [comment] 2023-11-09 19:25
From which frequency was this recorded? 101.5?

**Comment by Yurij20** [comment] 2023-11-09 19:31
102.5

**Comment by PE5PVB** [comment] 2023-11-09 19:59
Should be fixed.

**Comment by Yurij20** [comment] 2023-11-09 20:04
ok) I'm waiting for the firmware release, I'll check it

**Comment by Yurij20** [comment] 2023-11-10 04:09
checked, everything works thanks

**Closed as completed** 2023-11-10 04:08 UTC
