### ISSUE TITLE
Text ticker not optimized

### ISSUE THREAD

**Issue by RZCH-DX** [PE5PVB/TEF6686_ESP32#569] opened 2024-05-19 10:13 UTC
Hello,

The ticker feature is not very optimized. I have noticed some issues:

- If there is only one AF freq, it will appear two times in the advanced RDS view. 
- Radiotext repeats if it's terminated with 0x0D
- Ticker will sometimes scroll even if the text isn't overflowing the space
- Sometimes some character(s) is/are appended a few spaces after the RT. Retuning gets rid of it.

These issues seems to happen with all tickers in the firmware.
Tested with 2.10 RC3

All issues except the unnecessary scrolling were not present in version 2.00

Examples:
![tickerafrepeat](https://github.com/PE5PVB/TEF6686_ESP32/assets/170234623/e452f337-e2cc-47ed-9e73-e1cef3da7cbe)

![tickerrtrepeat](https://github.com/PE5PVB/TEF6686_ESP32/assets/170234623/d639dbfa-cb00-4b3f-8404-b8a58154a54b)
![rdsspy](https://github.com/PE5PVB/TEF6686_ESP32/assets/170234623/2c093cd7-50b1-44c7-ade8-03250a24e02d)

RT not scrolling but with trailing hyphen that should not be there:
https://youtu.be/cDeJrWqslc0

RT scrolling even if there's enough space for it without scrolling:
https://youtu.be/bzz1613KdZc

**Comment by PE5PVB** [comment] 2024-05-19 10:19
1.  This is caused by continiously scrolling. I will change this when only one AF is present.
2.  This is as expected. 
3.  It's difficult to determ the exact textlength, because fontwidth is dynamic. I had to set a rule for this.
4.  I think the radiostation is also transmitting RT method B without content.

**Comment by RZCH-DX** [comment] 2024-05-19 10:29
Hello Sjef,

Thank you for the quick reply. 

Regarding issue 2: It's confusing to see the same text two times. The start and end of the received RT is not clearly visible anymore. 
Maybe it's an option just to scroll until the last character is reached. Then restarting the ticker.

Issue 4: Do you mean RT in group 2B? The station is only transmitting 0A, 2A and 4A groups. No 2B.
It alternates between RT flag A and B, though with the same content as seen in the RDS spy screenshot.

**Comment by PE5PVB** [comment] 2024-05-19 10:32
Can you send me a MPX file of that channel?

**Comment by RZCH-DX** [comment] 2024-05-19 13:10
Yes, of course
[4f29190524.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/15369506/4f29190524.zip)

**Comment by PE5PVB** [comment] 2024-05-19 13:24
![image](https://github.com/PE5PVB/TEF6686_ESP32/assets/76666293/18cd3a0b-2b5b-491e-99ab-3f66d3aa0698)

Seems they broadcast a RT line starting with - sometimes. What other problems are hrere?

**Comment by RZCH-DX** [comment] 2024-05-19 13:29
Ah I didn't mean the hyphen at the beginning. The TEF handles this one without any problems.

I'm talking about this one, which is not transmitted and not seen in RDS spy:
![trailinghyphen](https://github.com/PE5PVB/TEF6686_ESP32/assets/170234623/395dd887-5289-49ed-92c9-b0ba50ece759)

**Comment by PE5PVB** [comment] 2024-05-19 13:33
OK. I watched the whole MPX sample you send me, but was not able to reproduce it.

**Comment by RZCH-DX** [comment] 2024-05-20 10:18
I've found a way to reproduce it. 

To reproduce it, you need a station which sends out 0x0D terminated RT, alternates between RT flag A/B and doesn't send anything (nothing, not even space letters) after 0x0D. (the majority of the NL stations seem to do it wrong)
You can use the MPX recording from before. It checks all the boxes.

1. Set "Show RDS errors" to "All" on the TEF
2. Null out the signal to the point where RDS is weak and spits out garbage.
3. Stay there for some seconds. 
4. Then move the antenna somewhere where the RDS signal is strong enough for errorless data. 
5. When the station sends a new RT flag, there will be random characters stuck from before. These characters are always after 0x0D.

This should not happen, a new RT flag should wipe out all previous data completely.

**Comment by PE5PVB** [comment] 2024-05-20 12:06
Well, if RT buffer is enabled you will always see the previous RT. So maybe that is what you have experienced. But you are right, currently the RT is not taking 0x0D as an end character, I'll fix that.

**Comment by RZCH-DX** [comment] 2024-05-20 12:47
RT buffer was disabled the entire time.

**Comment by RZCH-DX** [comment] 2024-05-22 16:40
With RC4, the DoubleAF-bug is fixed. But it's still present in the EON ticker.

The radiotext in the ticker now repeats even sooner. So this got worse.
![20240522_180005](https://github.com/PE5PVB/TEF6686_ESP32/assets/170234623/dc8c49d9-3c3f-41f5-84ae-4e1a7d6ad451)
![20240522_180215](https://github.com/PE5PVB/TEF6686_ESP32/assets/170234623/0f1d1f56-fe38-4ca2-9939-7c348d25fe80)

**Comment by PE5PVB** [comment] 2024-05-22 18:19
Fixed

**Comment by RZCH-DX** [comment] 2024-05-25 17:00
The unnecessary scrolling issue has been fixed with RC6.

The issue with the trailing characters which aren't going away with RT flag refresh is still there though.

**Comment by PE5PVB** [comment] 2024-05-25 17:02
> The issue with the trailing characters which aren't going away with RT flag refresh is still there though.

I need a MPX file to reproduce and fix that.

**Comment by lxsxl** [comment] 2024-05-25 19:38
The ODA-ticker in EON mode is very slow: it moves two or three characters, than stops for a moment, then the next few characters and so on.

**Comment by RZCH-DX** [comment] 2024-05-25 20:26
> > The issue with the trailing characters which aren't going away with RT flag refresh is still there though.
> 
> I need a MPX file to reproduce and fix that.

Use this MPX file and the following instruction to reproduce it
[4f382505242223.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/15444935/4f382505242223.zip)

> 1. Set "Show RDS errors" to "All" on the TEF
> 2. Null out the signal to the point where RDS is weak and spits out garbage.
> 3. Stay there for some seconds.
> 4. Then move the antenna somewhere where the RDS signal is strong enough for errorless data.
> 5. When the station sends a new RT flag, there will be random characters stuck from before. These characters are always after 0x0D.

**Comment by PE5PVB** [comment] 2024-05-26 12:05
OK. I added a detector which should delete all characters after the first find of 0x0d in the Radiotext.

**Comment by andimik** [comment] 2024-05-26 15:41
With RC7 from discord the ticker exceeds the "cell" in normal view and overlaps the flag dots. In advanced RDS view it's OK.

**Comment by PE5PVB** [comment] 2024-05-26 15:42
Yes I know. Already fixed.

**Comment by lxsxl** [comment] 2024-05-26 16:00
The continously scrolling texts are really great! I didn't see any problems with the last code.

**Comment by RZCH-DX** [comment] 2024-05-26 19:49
> OK. I added a detector which should delete all characters after the first find of 0x0d in the Radiotext.

It's still happening with the latest commit

**Comment by lxsxl** [comment] 2024-05-26 19:51
Does it really? Or is it only the same text that is displayed in a loop? This is intended!

**Comment by PE5PVB** [comment] 2024-05-26 20:22
Are you  able to monitor via Serial, like with Putty? in that case I can make a version for you with some debug output.

**Comment by RZCH-DX** [comment] 2024-05-26 20:23
> Does it really? Or is it only the same text that is displayed in a loop? This is intended!

No, it's not the same text. It's garbage data which is stuck in the RT ticker until retuning. 
Reproduce it with the instructions 7 comments above.

This also happens with stations without 0x0D. 
These garbage characters sometimes appear after the 64th character.

The station in the following video doesn't use 0x0D and always send out 64 characters in RT. I could produce some garbage with the method above, which cause the RT in the ticker to be longer than 64 characters. (Just count the dashes after "WORLD")
After retuning, garbage is gone and RT is 64 characters again.

https://youtu.be/TZc85ix_Nr8

Maybe this issue can be fixed by limiting the radiotext string to 64 characters.

**Comment by PE5PVB** [comment] 2024-05-26 20:26
Please check if you see the dot on 2B turn on. I think because of the worse signal in combination with show all errors, the receiver thinks there is a Radiotext 32 chars in group 2B and fills it with garbage. When 32 chars RT is detected, it is merged to the 64 character RT from group 2A.

**Comment by RZCH-DX** [comment] 2024-05-26 20:30
> Please check if you see the dot on 2B turn on. I think because of the worse signal in combination with show all errors, the receiver thinks there is a Radiotext 32 chars in group 2B and fills it with garbage. When 32 chars RT is detected, it is merged to the 64 character RT from group 2A.

Yes, 2B appears.

**Comment by PE5PVB** [comment] 2024-05-26 20:32
There is the problem. Note that when you set Show all errors, things like this can happen. What happens is that the wrong RDS group is processed. Can't fix that when the data is corrupt.

**Comment by RZCH-DX** [comment] 2024-05-26 20:35
Yes of course. But why is 2B-radiotext appended to 2A-radiotext? Wouldn't it be better if the 2B RT gets merged *into* the 2A RT?

**Comment by PE5PVB** [comment] 2024-05-26 20:46
Yes it is merged with 2A, but if the software detects a character at for example, position 20, then you have this result. That's why there is error correction on RDS. But if you switch it off........ ;-)

**Comment by RZCH-DX** [comment] 2024-05-26 20:59
> Yes it is merged with 2A, but if the software detects a character at for example, position 20, then you have this result. That's why there is error correction on RDS. But if you switch it off........ ;-)

Currently the entire 2B RT is just appended after the 64 characters of 2A RT.
Let's say the false 2B character at position 20 is Ä

Currently looks like this:

`Dua_Lipa_-_Houdini_(2023)_______________________________________ ___________________Ä____________`

instead of being merged into like here:

`Dua_Lipa_-_Houdini_Ä2023)_______________________________________`

The second approach make more sense in my opinion

**Comment by PE5PVB** [comment] 2024-05-26 21:02
You don't want to merge it like that. There are stations who sends different texts on 2A and 2B.

**Comment by RZCH-DX** [comment] 2024-05-26 21:03
> You don't want to merge it like that. There are stations who sends different texts on 2A and 2B.

All right, understood. Then everything is resolved for me. Thank you very much!

**Closed as completed** 2024-05-26 21:03 UTC
