### ISSUE TITLE
No sound during SW auto tuning after turning on the screen

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#607] opened 2024-06-08 16:41 UTC
If I turn off the display in the SW band and start automatic tuning with the encoder and turn on the display during tuning, the tuning stops at the current frequency, but the sound remains muted.

**Comment by Mike86-CZE** [comment] 2024-06-08 18:11
And I remind you that the beep still does not work for SW bands when the screen is off.  It was already fixed once, but the problem reappeared over time.

**Comment by PE5PVB** [comment] 2024-06-08 18:16
I can't reproduce this problem. Please let me know which menu settings I should have and then a step-by-step plan to reproduce.

**Comment by Mike86-CZE** [comment] 2024-06-08 18:27
![20240608_202121](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/6db83245-b96a-44ba-8558-1009837f7193)
![20240608_202152](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/5f677ca8-69ba-4420-ba5f-05d3892ef3ec)
![20240608_202212](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/a1a73e93-4e9f-4c7a-8d50-e0544b3dec0e)
![20240608_202325](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/08b46ddc-e986-44d4-ae69-9809b132c6ee)
![20240608_202344](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/ab1d670d-2848-4281-8ca5-e902ea0a187e)
![20240608_202412](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/d2ef59c4-7dfe-4a7e-977c-962053148c1b)
![20240608_202435](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/b0503011-e9b6-4de4-b291-ea9b3d0b4921)
![20240608_202456](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/70d29507-dd18-4f9c-8b0f-ad30f7db0e16)

**Comment by PE5PVB** [comment] 2024-06-08 18:32
OK. And how to reproduce?

**Comment by Mike86-CZE** [comment] 2024-06-08 18:34
1. switch to the SW band
2. set the tuning mode to AUTO
3. turn off the display by holding down the BAND button
4. turn the encoder to start tuning 
5. before a station has time to tune in, turn on the display with the BAND button 
6. the tuning has stopped at some frequency, but the sound  did not activate

**Comment by Mike86-CZE** [comment] 2024-06-08 18:42
The correct behavior would be to not stop tuning at all after turning on the display and continue to search for a station.

**Comment by PE5PVB** [comment] 2024-06-08 22:22
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/646460306b1b57c3f05238d339334d6ad5ce674f

**Comment by numerci** [comment] 2024-06-11 05:36
This seem to be working fine for me now on RC15

**Closed as completed** 2024-06-12 09:33 UTC
